services:
  backend:
    build: ./backend
    image: mern-backend:jenkins
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://localhost:5000/api"
    image: mern-frontend:jenkins
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always